
WITH selection AS
(
WITH co AS
(
SELECT icu.subject_id, icu.hadm_id, icu.icustay_id, dx.icd9_code, pat.dob
, EXTRACT(EPOCH FROM outtime - intime)/60.0/60.0 as icu_length_of_stay_h
, EXTRACT('epoch' from icu.intime - pat.dob) / 60.0 / 60.0 / 24.0 / 365.242 as age
, RANK() OVER (PARTITION BY icu.subject_id ORDER BY icu.intime) AS icustay_id_order
, admissions.diagnosis, admissions.admission_type, admissions.admittime, admissions.dischtime

FROM icustays icu
INNER JOIN patients pat
  ON icu.subject_id = pat.subject_id
INNER JOIN diagnoses_icd dx
  ON icu.hadm_id = dx.hadm_id
INNER JOIN admissions admissions
  ON icu.hadm_id = admissions.hadm_id
)

SELECT
  co.subject_id, co.hadm_id, co.icustay_id, co.admittime, co.dischtime, co.dob, co.icu_length_of_stay_h
  , co.age
  , co.icustay_id_order
  , co.icd9_code
  , co.admission_type
  , co.diagnosis as admission_dx
  , CASE
    WHEN co.icu_length_of_stay_h < 12 then 1
    ELSE 0 END
    AS exclusion_los
  , CASE
        WHEN co.age < 17 then 1
    ELSE 0 END
    AS exclusion_age
  , CASE
        WHEN co.icustay_id_order != 1 THEN 1
    ELSE 0 END
    AS exclusion_first_stay
  , CASE
        WHEN co.icd9_code LIKE '433%' OR co.icd9_code LIKE '434%' OR co.icd9_code LIKE '436%'  THEN 0
    ELSE 1 END
    AS exclusion_discharge_diagnosis

  , CASE
        WHEN co.admission_type = 'EMERGENCY' OR co.admission_type = 'URGENT' THEN 0
        ELSE 1 END
    AS exclusion_non_urgent

    , CASE
        WHEN LOWER(co.diagnosis) LIKE '%stroke%' OR LOWER(co.diagnosis) LIKE '%cva%'
        OR co.diagnosis IN ('STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK','STROKE/TIA','CEREBROVASCULAR ACCIDENT','STROKE;TELEMETRY','STROKE;TELEMETRY;TELEMETRY','STROKE','STROKE-TRANSIENT ISCHEMIC ATTACK','CEREBRAL VASCULAR ACCIDENT','BRAIN STEM STROKE','TRANSIENT ISCHEMIC ATTACK','CEREBELLAR INFARCT','ACUTE STROKE','STROKE;TELEMETRY; TIA','STROKE;TIA','RIGHT FACIAL DROOP','STROKE;TRANSIENT ISCHEMIC ATTACK','ARTERIAL OCCLUSION','R/O STROKE','CEREBROVASCULAR ACCIDENT;TELEMETRY','STROKE,TRANSIENT ISCHEMIC ATTACK','LEFT CEBELLAR ISCHEMIC STROKE','CEREBELLAR INFACTS','STROKE;TELEMETRY;TELEMETRY;TELEMETRY','UNRESPONSIVENESS, CVA VS. SEIZURE','NEW CVA','LEFT OCCIPITAL STROKE','AORTIC DISSECTION;STROKE','CEREBRAL VASCULAR ACCIDENT;HYPERCARBIA','LT ARM WEAKNESS;R/P CVA','STROKE;RHABDO,URINARY TRACT INFECTION','SRTROKE/TIA','CONFUDION, TEMPORAL MASS/STROKE','CEREBELUM STROKE','ACUTE CVA','ISCHEMIC STROKE','STROKE WITH HEAD BLEEDVERTEBRAL DISSECTION;STROKE;TELEMETRY','S/P STROKE','TIA','STROKE;TELEMETRY; TRANSIENT ISCHEMIC ATTACK','APHASIA','RIGHT SIDED WEAKNESS;ANEMIA','STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK;TELEMETRY','ACUTE ISCHEMIC STROKE','DEEP VEIN THROMBOSIS;LEFT LEG WEAKNESS','RIGHT MCA STROKE','ACUTE STROKE;TELEMETRY','CORONARY ARTERY DISEASE;TRANSIENT ISCHEMIC ATTACK','MCA;STROKE','STROKE,MI','MCA STOKE S/P THROMBOLYSIS','CVA, BRADYCARDIA','LEFT PCA STROKE','THROMBOTIC THROMBOCYTOPENIC PUPURA;? STROKE','STROKE /TIA','BILATERAL CEREBELLAR STROKE','CEREBELLAR INFARCTION','ACUTE CVA;TELEMETRY? CVA','STROKE/ TIA','CEREBELLAR CVA','CEREBRAL VASCULAR ACCIDENT VS TRANSIENT ISCHEMIC ATTACK','CVA;HYPOTENSION','L SIDED WEAKNESS','CEREBROVASCULAR ACCIDENT;CAROTID DISSECTION','CEREBROVASCULAR ACCIDENT;FEV','STRUKE','RIGHT LEG WEAKNESS;DEMENTIA','BRAIN STEM CVA','RIGHT ARM  WEAKNESS','RT MCA STROKE','UNRESPONSIVE/? STROKE','STROKE; TIA','MCA STROKE','CEREBELLER STOKE','CVA;TELEMETRY','BASILAR STROKE','CN 111 PALSY','TRANSIENT ISCHEMIC ATTACK;ICA CLOT','DYSPHASIA','STROKE-R/O VASCULITIS','SUBCORTICAL STROKE','BASILLAR OCCLUSION','VERTEBRAL ARTERY DISSECTION','CEREBRALVASCULAR ACCIDENT','CEREBROVASCULAR ACCIDENT-RT HEMIPARESIS','VERTEBRAL ARTERY OCCLUSION','CODE STROKE','RULE-OUT MYOCARDIAL INFARCTION;TELEMETRY;?CVA','CEREBROBASVULAR ACCIDENT','STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK;SHINGLES','R/O CVA','LT SIDED STROKE','LEFT CEREBRAL VASCULAR ACCIDENT','UNABLE TO AMBULATE','PONTINE STROKE','CEREBRO VASCULAR ACCIDENT','STROKE.TIA','MYOCARDIAL INFARCTION;STROKE','SLURRED SPEACH;R/O STROKE','CEREBRAL INFARCT','RIGHT POST CIRCULATING ARTERY STROKE','ENCEPHALOPATHY','ACUTE CEREBRAL VASCULAR ACCIDENT','RIGHT ANTERIOR CEREBRAL ARTERY STROKE','VERTEBRAL ARTEY DISSECTION','CEREBRAL VASCULAR ACCIDENT VS SEIZURE','S/P FAL','RIGHT MIDDLE CEREBRAL ARTERY STROKE','FAILURE TO THRIVE;VOMITING','CHEST PAIN,ARM NUMBNESS','MENTAL STATUS CHANGE','VERTIGO','CVA VS.SEIZURES','LEFT CVA','STRIKE;TRANSIENT ISCHEMIC ATTACK','MCA STROKE;COMP SYNDROME;RHABDOMYOLISIS','CORONARY ARTERY DISEASE;TIA','FALL','RIGHT MCA STROKE;TELEMETRY','R/O CVA;SYNCOPE','R/O VERTEBRAL ARTERY DISSECTION','R/O CEREBROVASCULAR ACCIDENT','WEAKNESS;RULE-OUT MYOCARDIAL INFARCTION','MENTAL STATUS CHANGES','RULE-OUT MYOCARDIAL INFARCTION;TELEMETRY;CVASEIZURE;STROKE;TELEMETRY;TELEMETRY','RIGHT-SIDED WEAKNESS','TRANSIENT ISCHEMIC ATTACK\CAROTID STENT','CORONARY ARTERY DISEASE;TIA;CAROTID STENOSIS\CATH/STENT PLACEMENTCVA,INTRACRANIAL HEMORAGE','DEMENTIA;FALLS','HEMIPLEGIA','CEREBRAL VASCULAR ACCIDENT;RESPIRATORY FAILURE;RAPIDN A-FIB','SECOND DEGREE BLOCK;? STROKE','BASILAR THROMBOSIS','STOKE;TRANSIENT ISCHEMIC ATTACK','LEFT SIDED HEMIPARESIS','R-SIDED WEAKNESS','STROKE;TELEMETRY;TRANSINET ISCHEMIC ATTACK','STROKE,TIA','CHANGE IN MENTAL STATUS','TIA;A-FIB','ALTERED MENTAL STATUS','LEFT MIDDLE CEREBRAL ARTERY STROKE;R/O MI','STROKE,DEHYDRATION,ALTERED MENTAL STATUS','STROKE,RIGHT MCA','SUBACUTE STROKE','WEAKNESS;TELEMTRY','LEFT SIDED CVA','VERTEBRAL BASALAR INSUFFICENCY/SDA','CEREBROVASCULAR ACCIDENT;PNEUMONIA','STROKE,ENDOCARDITIS','APNEA,MENTAL STATUS CHANGES','TRANSIENT ISCHEMIC ATTACK; CVA','ACUTE CEREBRAL INFARCTION','LEFT SIDED WEAKNESS;BRADYCARDIA','CEREBROVASCULAR ACCIDENT;S/P TPA','FEVER;? CVA','S/P CVA;CAROTID STENOSIS\CAROTID ANGIOGRAM','RT CEREBELLAR INFARCTION','CEREBRAL VASCULAR ACCIDENT-R/O MYOCARDIAL INFARCTION','BASAL STEM STROKE') THEN 0
        ELSE 1 END
    AS exclusion_admission_diagnosis

FROM co
)
